### ISSUE TITLE
Error on puppet:///modules/common/empty

### ISSUE THREAD

**Issue by spikelab** [duritong/puppet-nagios#1]
Hi,

I'm getting the following error:

> err: Could not run Puppet configuration client: Could not retrieve information from source(s) puppet:///modules/common/empty at /etc/puppet/modules/common/nagios/manifests/base.pp:73

I don't understand the meaning of _modules/common/empty_, is it supposed to be replaced by something else?

Thanks

**Comment by duritong** [comment]
This is an empty directory as supplied with my common module: https://github.com/duritong/puppet-common

**Comment by spikelab** [comment]
Ah, I see. This doesn't make the module very portable in my opinion, not as much because of the dependency itself but rather because the dependent module is named like something you're guaranteed most people will have and as such will clash. Could you explain me what is the benefit of having the source specified?

Thanks

**Comment by duritong** [comment]
http://christian.hofstaedtler.name/blog/2008/11/puppet-managing-directories-recursively.html

Regarding the name: For a module that contains common things, as my common module does, it is always likely that there will be a naming clash.

**Comment by spikelab** [comment]
It is my understanding that this is no longer necessary since 0.26. I appreciate the will to be backward compatible for the people still on 0.25, but at this stage I'd rather fork it and remove the source statement than having to depend on yet another module. Thank you.

**Comment by duritong** [comment]
Indeed this is not anymore necessary on 2.6 and I simply didn't remove it yet. But given that the module started during 0.24.x times I would happily non-invasive cleanup patches.

**Comment by spikelab** [comment]
ok, I've forked the project and I'm doing some work on it which I'll be pushing hopefully in the next few days once I've tested it. Feel free to cherry pick any change you deem appropriate. Thanks.
