### ISSUE TITLE
err: Could not run Puppet configuration client: Could not find init script for 'nagios3

### ISSUE THREAD

**Issue by spikelab** [duritong/puppet-nagios#2]
> debug: Service[nagios](provider=debian): Could not find nagios3 in /etc/init.d
> debug: Service[nagios](provider=debian): Could not find nagios3.sh in /etc/init.d
> debug: report supports formats: b64_zlib_yaml marshal raw yaml; using marshal
> err: Could not run Puppet configuration client: Could not find init script for 'nagios3'

I'm running ubuntu which works fine provided you add "ubuntu" to the case statement in init.pp (patch coming). Unfortunately I then get that error which I'm not being able to track down. It seems to be related to the class inheritance between debian and base. If in base I change the name of the package and the service to _nagios3_ it will then work fine (only to a certain extent actually, it blows up some other place later on, but that's something else)

any idea what that might be? Thanks

**Comment by duritong** [comment]
I don't know about nagios on ubuntu, but how is the init.d script called? Because this is what puppet is complaining about.

It looks like on debian the init script is called nagios3, therefore we do the overwrite on https://github.com/duritong/puppet-nagios/blob/master/manifests/debian.pp#L10

Maybe you will need to have a simple ubuntu subclass of debian that renames it back to nagios (doh...) as maybe ubuntu needs the other adjustments.

**Comment by spikelab** [comment]
Apologies, it sounds like I didn't explain myself. The init script on ubuntu is called nagios3 like on debian, and pretty much everything else seems to be the same too.

> monitor2:/etc/puppet/modules/common/nagios# dpkg -L nagios3-common | grep init
> /etc/init.d
> /etc/init.d/nagios3

The problem is rather that the Require['nagios'] on the Service['nagios'] in debian.pp does not seem to take effect and for some reason puppet thinks the package is installed so when the the service tries to start it, it fails because indeed the init script is not there. I've no idea why this happens, the code seems correct to me, but clearly it doesn't work. It seems to be some kind of problem with inheritance and overrides because if I manually set the package resource to nagios3 in base.pp it starts working. This is on a fresh install of ubuntu lucid. Thanks.

**Comment by duritong** [comment]
Unfortunately I don't have a ubuntu version to test.

**Comment by lelutin** [comment]
Hi, I dug around for the reason of this error. I saw this also in Debian Squeeze with puppet 2.6.2.

Removing "hasstatus" in debian.pp makes the module work again.

and ... with puppet 2.7.6, this problem simply doesn't show. So I guess it's a bug with puppet 2.6.x
