### ISSUE TITLE
It seems not work on ubuntu

### ISSUE THREAD

**Issue by jeffrey4l** [duritong/puppet-nagios#6]
On ubuntu, the `operationsystem=Ubuntu`. So it doesn't work. I think the `osfamily` should be used.

**Comment by duritong** [comment]
or add 'ubuntu' to the  'debian': { part.

Pullrequest?

**Comment by jeffrey4l** [comment]
I am Sorry. Just now, I have no time to add some pull request.

**Comment by duritong** [comment]
And I have no ubuntu to test it.
